site_name: Linux
theme:
  name: 'material'
extra_css:
- ./css/extra.css
# #  - css/second_extra.css
nav:
- Home: 'index.md'
- Introducción:
    - Part1 : 
      - writing:
        - 'Writing your docs': 'writing-your-docs.md'
    - 'Styling your docs': 'styling-your-docs.md'
- Acerca:
    - 'About me': 'license.md'
    - 'ACECOM': 'release-notes.md'
