site_name: Linux
theme:
  name: 'material'
  feature:
      tabs: false
  static_templates:
    - sitemap.html
extra_css:
- css/extra.css
nav:
- Home: 'index.md'
- Introducción:
  - 'Guia': 'introduction/guide.md'
- Primera Parte : 
  - Arquitectura:
    - 'Proceso de Booteo': 'primera-parte/1-Arquitecture.md'
  - Instalación de Linux:
    - 'Creación de USB boot': 'primera-parte/2-USBBoot/index.md'
    - 'Particiones': 'primera-parte/2-Partitions.md'
    - 'Instalación Ubuntu': 'primera-parte/2-Install-Ubuntu.md'
    - 'Instalación Fedora': 'primera-parte/2-Install-Fedora.md'
    - 'Instalación Kali': 'primera-parte/2-Install-Kali.md'
  - Comandos Unix y GNU:
    - 'Comandos UNIX': 'primera-parte/3-UnixCommands.md'
  - Gestión de software y procesos:
    - 'Gestión de paquetes': 'primera-parte/4-PackageManaging.md'
  - Configuración de Hardware:
    - 'Configuraciones': 'primera-parte/5-HardwareConfigurations.md'
  - Gestión de Archivos:
    - 'File Management': 'primera-parte/6-ManagingFiles.md'
#   - Sistema de Archivos: ''  
# - Segunda Parte:
#     - 

- Acerca:
    - 'About me': 'license.md'
    - 'ACECOM': 'release-notes.md'


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true