site_name: Linux
theme:
  name: 'material'
  feature:
      tabs: false
extra_css:
- css/extra.css
nav:
- Home: 'index.md'
- Introducción:
  - 'Guia': 'introduction/guide.md'
- Primera Parte : 
  - Arquitectura:
    - 'Proceso de Booteo': 'part1/arquitectura.md'
  - Instalación de Linux:
    - 'Writing your docs': 'writing-your-docs.md'
  - Gestión de paquetes:
    - 'Writing your docs': 'writing-your-docs.md'
  - Comandos Unix y GNU:
    - 'Comandos UNIX': 'part1/unixCommands.md'
#   - Sistema de Archivos: ''  
# - Segunda Parte:
#     - 

- Acerca:
    - 'About me': 'license.md'
    - 'ACECOM': 'release-notes.md'


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true